const Images = {
  mainScreen: require('../Assets/Images/border.jpg'),
  splash: require('../Assets/Images/ic_splash_bg.png'),
  splashLogo:require('../Assets/Images/ic_splash_mosologo.png'),
  TutorialScreen1:require('../Assets/Images/ic_loginoption_bg.png'),
  TutorialScreen2:require('../Assets/Images/ic_loginoption_explore_bg.png'),
  TutorialScreen3:require('../Assets/Images/ic_loginoption_connect_bg.png'),
  TutorialScreen4:require('../Assets/Images/ic_loginoption_grow_bg.png'),
  fb:require('../Assets/Images/ic_loginoption_fb.png'),
  linkedIn:require('../Assets/Images/linkedin.png'),
  swipe:require('../Assets/Images/ic_loginoption_swipe.png'),
  loginImage:require('../Assets/Images/ic_email_login_bg.png'),
  forgotPasswordImage:require('../Assets/Images/ic_forgot_password_illustration.png'),
  forgotPasswordBackArrow:require('../Assets/Images/ic_forgot_password_back.png'),
  resetPasswordKey:require('../Assets/Images/ic_reset_password_illustration.png'),
  verifiedSuccesfully:require('../Assets/Images/ic_verified_successfully_tick.png'),
  blurMapBackground:require('../Assets/Images/blur_map_background.png'),
  menuIcon:require('../Assets/Images/ic_home_menu.png'),
  searchIcon:require('../Assets/Images/ic_home_search.png'),
  placeholderImage:require('../Assets/Images/placeholder.jpg'),
  searchPin:require('../Assets/Images/ic_home_search_pin.png'),
  homePageDisableIcon:require('../Assets/Images/ic_home_disable_event.png'),
  mapPageDisableIcon:require('../Assets/Images/ic_home_disable_map.png'),
  homePageIcon:require('../Assets/Images/ic_home_enable_event.png'),
  mapPageIcon:require('../Assets/Images/ic_home_enable_map.png'),
  user:require('../Assets/Images/lady.png'),
  searchPinInMap:require('../Assets/Images/icon4_without_gredient.png'),
  camera:require('../Assets/Images/ic_signup_camera.png'),
  approved:require('../Assets/Images/ic_signup_approve.png'),
  blurredMap:require('../Assets/Images/ic_map_bg.png'),
};

export default Images;
